# Generated by Django 4.1.7 on 2023-03-28 06:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("photo", models.ImageField(upload_to="blog/images/")),
                ("short_discription", models.TextField()),
                ("discription", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
